// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBR7cM-OFjA12dGkrDxCjOgaWHcKVrts',
    appId: '1:119371938355:web:69f98085ae6e1df739c146',
    messagingSenderId: '119371938355',
    projectId: 'qurban-mart',
    authDomain: 'qurban-mart.firebaseapp.com',
    storageBucket: 'qurban-mart.appspot.com',
    measurementId: 'G-LYF9522JZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfefIWvLD0EOfBfMQQcQimwyWJxMfywFA',
    appId: '1:119371938355:android:ef283b713191811639c146',
    messagingSenderId: '119371938355',
    projectId: 'qurban-mart',
    storageBucket: 'qurban-mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5EZfAHGhoIE-0UO-n_jDzaBQ2KnTxpI',
    appId: '1:119371938355:ios:6bd90ed63e02be0139c146',
    messagingSenderId: '119371938355',
    projectId: 'qurban-mart',
    storageBucket: 'qurban-mart.appspot.com',
    iosBundleId: 'com.example.qurbanMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5EZfAHGhoIE-0UO-n_jDzaBQ2KnTxpI',
    appId: '1:119371938355:ios:6bd90ed63e02be0139c146',
    messagingSenderId: '119371938355',
    projectId: 'qurban-mart',
    storageBucket: 'qurban-mart.appspot.com',
    iosBundleId: 'com.example.qurbanMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIBR7cM-OFjA12dGkrDxCjOgaWHcKVrts',
    appId: '1:119371938355:web:317eb09d6efce58e39c146',
    messagingSenderId: '119371938355',
    projectId: 'qurban-mart',
    authDomain: 'qurban-mart.firebaseapp.com',
    storageBucket: 'qurban-mart.appspot.com',
    measurementId: 'G-RHGSZD3RRK',
  );
}
